read consistency level fix
lancedb/lancedb pull request #1567
Opened 2024-08-27 01:28 UTC by gagan-bhullar-tech

PR fixes #1565

2024-08-27 02:19 UTC, gagan-bhullar-tech commented
@wjones127 please review.

2024-08-27 20:45 UTC, wjones127 requested changes

2024-08-27 20:45 UTC, wjones127 commented on node/src/test/test.ts
> +      await table1.add([
We should make this test more robust by asserting the state before the change as well:
```suggestion
      assert.equal(await table2.countRows(), 2);
      await table1.add([
```

2024-08-27 22:27 UTC, gagan-bhullar-tech commented
@wjones127 Updated PR. Please review.

2024-08-28 00:03 UTC, wjones127 approved these changes

2024-08-28 00:03 UTC, wjones127 commented
Thanks @gagan-bhullar-tech !

2024-08-28 00:03 UTC, merged