expose hnsw indices in nodejs
lancedb/lancedb pull request #1595
Opened 2024-09-04 06:15 UTC by gagan-bhullar-tech

PR closes #1522

2024-09-04 06:34 UTC, gagan-bhullar-tech commented
@wjones127 can you please review PR. I will create a separate PR for python. Thanks.

2024-09-05 04:01 UTC, gagan-bhullar-tech commented
@wjones127 can you please review PR.

2024-09-05 15:50 UTC, wjones127 reviewed
@gagan-bhullar-tech HNSW indices have several configuration options such as `m`, `m_max`, `ef_construction`. These already exist here: https://github.com/lancedb/lancedb/commit/5e0181043845afd61c4de32e3ef05acef87f495b

2024-09-05 15:50 UTC, wjones127 commented on python/src/index.rs
> +    pub fn hnswsq() -> PyResult<Self> {
We should be able to set the parameters for these. See `ivf_pq` method above.

2024-09-07 00:03 UTC, gagan-bhullar-tech commented
@wjones127 @westonpace can you please review.

2024-09-09 18:54 UTC, wjones127 requested changes
HNSW and PQ and SQ are each their own "word", so please capitalize the variables names appropriately. Be consistent with how we handle `IVF_PQ` indices.

It looks like you've added all the options. But they are not documented. I'm fine with leaving the documentation for a future PR.

2024-09-09 18:54 UTC, wjones127 commented on nodejs/lancedb/indices.ts
> +  static hnswpq(options?: Partial<HnswPqOptions>) {
To be consistent with other camel case names:
```suggestion
  static hnswPq(options?: Partial<HnswPqOptions>) {
```

2024-09-09 18:54 UTC, wjones127 commented on nodejs/lancedb/indices.ts
> +  static hnswsq(options?: Partial<HnswSqOptions>) {
```suggestion
  static hnswSq(options?: Partial<HnswSqOptions>) {
```

2024-09-09 18:54 UTC, wjones127 commented on python/python/lancedb/index.py
> +class Hnswpq:
```suggestion
class HnswPq:
```

2024-09-09 18:54 UTC, wjones127 commented on python/python/lancedb/index.py
> +class Hnswsq:
```suggestion
class HnswSq:
```

2024-09-09 18:54 UTC, wjones127 commented on python/python/lancedb/index.py
> +    """Describe a Hnswsq index configuration."""
```suggestion
    """Describe a HNSW-SQ index configuration."""
```

2024-09-10 06:47 UTC, gagan-bhullar-tech commented
@wjones127 please review

2024-09-10 17:48 UTC, wjones127 approved these changes
This is looking good now. I can fix the merge conflict in a minute.

2024-09-10 17:53 UTC, wjones127 commented
Added a follow up issue for documentation: https://github.com/lancedb/lancedb/issues/1627

2024-09-10 18:08 UTC, merged