feat: HNSW default partitions
lancedb/lancedb pull request #1667
Opened 2024-09-19 03:08 UTC by gagan-bhullar-tech

2024-09-24 02:41 UTC, gagan-bhullar-tech commented
@wjones127 please review

2024-09-24 15:22 UTC, wjones127 requested changes
Thanks for working on this. Have a few suggestions.

2024-09-24 15:22 UTC, wjones127 commented on rust/lancedb/src/index/vector.rs
> +    let num_partitions = ((rows as f64) * (dim as f64)).div((256 * 5000000) as f64) as u32;
I would keep as an integer. u64 should be enough.
```suggestion
    let num_partitions = (((rows as u64) * (dim as u64)) / (256 * 5_000_000)) as u32;
```

2024-09-24 15:22 UTC, wjones127 commented on rust/lancedb/src/table.rs
> +        };
Could you do the same in `create_ivf_hnsw_sq_index`?

2024-09-24 15:22 UTC, wjones127 commented on rust/lancedb/src/table.rs
> +            suggested_num_partitions_for_hnsw(self.count_rows(None).await?, num_sub_vectors)
I think `dims` was meant to be original dimensions, not the compressed subvectors. Could you get that? It's the `n` inside of the `arrow_schema::DataType::FixedSizeList`

2024-09-25 02:06 UTC, gagan-bhullar-tech commented
@wjones127 updated PR. Can you please review.

2024-09-25 16:15 UTC, wjones127 approved these changes

2024-09-25 16:16 UTC, merged