Feat :- Adding ignore_missing to async drop_table() method
lancedb/lancedb pull request #1953
Opened 2024-12-18 05:11 UTC by nakul-py

**Adding `ignore_missing` to async `drop_table()` method**

Fixes #1951

2024-12-18 16:42 UTC, wjones127 requested changes
Hi @nakul-py, thanks for working on this!

Could you:

1. Add an async python test for this. Basically needs to be an async version of this test: https://github.com/lancedb/lancedb/blob/37c359ed40e860d8f2eec3b72e53ab91a6ad82c8/python/python/tests/test_db.py#L485-L508
2. Replace the sync implementation to simply dispatch to the async one. Basically this: https://github.com/lancedb/lancedb/blob/37c359ed40e860d8f2eec3b72e53ab91a6ad82c8/python/python/lancedb/db.py#L506-L512 Can be replaced with
```python
        LOOP.run(self._conn.drop_table(name, ignore_missing=ignore_missing))
```

2024-12-18 16:43 UTC, wjones127 commented on python/python/lancedb/db.py
> +    async def drop_table(self, name: str, ignore_missing: bool = False):
Also, let's make this kwarg-only in the async API:
```suggestion
    async def drop_table(self, name: str, *, ignore_missing: bool = False):
```

2024-12-19 08:05 UTC, nakul-py commented
> Hi @nakul-py, thanks for working on this!
> 
> Could you:
> 
> 1. Add an async python test for this. Basically needs to be an async version of this test: https://github.com/lancedb/lancedb/blob/37c359ed40e860d8f2eec3b72e53ab91a6ad82c8/python/python/tests/test_db.py#L485-L508
> 2. Replace the sync implementation to simply dispatch to the async one. Basically this: https://github.com/lancedb/lancedb/blob/37c359ed40e860d8f2eec3b72e53ab91a6ad82c8/python/python/lancedb/db.py#L506-L512
>     Can be replaced with
> 
> ```python
>         LOOP.run(self._conn.drop_table(name, ignore_missing=ignore_missing))
> ```

Can be complete with other PR

2024-12-19 16:45 UTC, wjones127 commented
> Can be complete with other PR

At the very least, I do not accept code changes that do not have unit tests.

2024-12-23 18:01 UTC, wjones127 reviewed
Thanks for adding a test. However, it doesn't look like it is passing. You can run this command to run that specific test locally:

```shell
pytest python/tests/test_db.py::test_delete_table_async
```

2024-12-24 08:29 UTC, nakul-py commented
Hey @wjones127  
Thanks! for remind me about running test locally. As i got many errors by running all code at sametime. I got so confused.
Now i have run this test seperately and it passed.  

This commit  will close this issue https://github.com/lancedb/lancedb/pull/1953/commits/7c20ca4f651af46bb24323ac3babf1d7cb35e66b

2024-12-24 18:33 UTC, wjones127 approved these changes
Thanks @nakul-py

2024-12-24 18:33 UTC, merged