flatten in async
lancedb/lancedb pull request #1967
Opened 2024-12-20 03:38 UTC by gagan-bhullar-tech

PR fixes #1949

2024-12-23 17:16 UTC, wjones127 requested changes
Thanks for working on this, @gagan-bhullar-tech 

Could you also add a unit test for `AsyncQuery.to_pandas()`?

2024-12-23 17:16 UTC, wjones127 commented on python/python/lancedb/query.py
> +
Why is this on `explain_plan`? Shouldn't it be in the `to_pandas()` section?

2024-12-23 17:16 UTC, wjones127 commented on python/python/lancedb/util.py
> +            specified depth.
```suggestion
    Flatten all struct columns in a table.

    Parameters
    ----------
    flatten: Optional[Union[int, bool]]
        If flatten is True, flatten all nested columns.
        If flatten is an integer, flatten the nested columns up to the
        specified depth.
```

2024-12-25 00:16 UTC, gagan-bhullar-tech commented
@wjones127 please review

2025-01-06 18:52 UTC, merged