Do not enforce limit
lancedb/lancedb pull request #1984
Opened 2024-12-26 16:10 UTC by alikefia

2024-12-26 16:11 UTC, alikefia commented
Fix #1983

2024-12-26 16:20 UTC, changhiskhan requested changes
Not having a default limit doesn't really make sense for vector search. This would also be a breaking change that would catch a lot of users by surprise. Is this just for consistency between vector vs non-vector query? Or do you need a total ordering of the table based on distance from a query vector?

2024-12-26 16:34 UTC, alikefia commented
Nope, the default is enforced here: https://github.com/lancedb/lancedb/blob/main/rust/lancedb/src/table.rs#L1928

2024-12-26 16:41 UTC, alikefia commented
Double checked :)

2024-12-26 22:39 UTC, alikefia commented
Added tests

2024-12-28 08:17 UTC, alikefia commented
@changhiskhan there is more to check on that one? It is blocking for us for consolidation jobs (copying full tables). Thx for support.

2024-12-29 19:04 UTC, alikefia commented
Fixed remote table defaults

2025-01-03 20:44 UTC, alikefia commented
Guys, can you please run the ci pipeline on that one ? Thx a lot !

2025-01-06 20:19 UTC, bfcrampton commented
Fixes https://github.com/lancedb/lancedb/issues/1852

2025-01-07 19:46 UTC, wjones127 reviewed
This looks reasonable. But I think you should update the docs as well.

2025-01-08 18:19 UTC, alikefia commented
The proposed implem is aligned with the doc so far 
- https://github.com/lancedb/lancedb/blob/main/rust/lancedb/src/query.rs#L346
- https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/query.py#L1481
- https://github.com/lancedb/lancedb/blob/main/nodejs/lancedb/query.ts#L232

This is why for me, it is more a bug fix than a change on the API

2025-01-08 23:15 UTC, wjones127 approved these changes
I see. Those are documented correctly then.

2025-01-08 23:16 UTC, wjones127 commented
@changhiskhan you have any further objection?

2025-01-09 00:05 UTC, judahrand commented
> The proposed implem is aligned with the doc so far
> 
> * https://github.com/lancedb/lancedb/blob/main/rust/lancedb/src/query.rs#L346
> * https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/query.py#L1481
> * https://github.com/lancedb/lancedb/blob/main/nodejs/lancedb/query.ts#L232
> 
> This is why for me, it is more a bug fix than a change to the API

I was referring to the docs on lancedb.query.LanceQueryBuilder found here https://lancedb.github.io/lancedb/python/python/#lancedb.query.LanceQueryBuilder.limit

2025-01-09 09:38 UTC, alikefia commented
@judahrand : indeed. I aligned to others for more consistency.

2025-01-10 14:16 UTC, alikefia commented
@changhiskhan any update on that ?

2025-01-13 21:56 UTC, wjones127 commented on rust/lancedb/src/remote/table.rs
> +
This is only applied to remote queries, not to local lanceDB ones.

Instead, I think the appropriate place to apply the default limit is when either `nearest_to()` or `full_text_search()` is called. That should capture both local and remote queries.

2025-02-26 18:46 UTC, closed without merging